### ISSUE TITLE
Issues with the different multi-tab informations

### ISSUE THREAD

**Issue by TLGYmc** [BentoBoxWorld/docs#26]
### Expected behavior

To be able to go backwards and forwards on the different tabs to see the information

### Observed/Actual behavior

With bigger text in the buttons, I am unable to go back to earlier tabs.

### Steps/models to reproduce

https://docs.bentobox.world/en/latest/gamemodes/AOneBlock/#phase-config-files
Press on "end-commands"
Try to go back to "name"

### BentoBox version

N/A

### Plugin list

N/A

### Other

Suggest adding some sort of backwards and forwards buttons or setting the current selected one to be in the middle?

**Comment by tastybento** [comment]
Can you use the left and right arrows on your keyboard? Or if you have a trackpad, scroll left or right using it?

https://github.com/BentoBoxWorld/docs/assets/4407265/7ebe1dd3-338b-4477-9696-514d4e7a6f5f

**Comment by TLGYmc** [comment]
I am able to use the left and right arrows on the keyboard but users wouldn't be able to easily find that.

**Comment by tastybento** [comment]
The theme is unfortunately a generic one and I don't know how to change it. Arrow keys are available, so I'm afraid this is a won't fix.
